[build-system]
requires = [
    "setuptools >= 61.0.0",
    "wheel",
    "numpy >= 1.25"
    ]
build-backend = "setuptools.build_meta"

[project]
name = "Kmars_test_1"
version = "0.1.0"
authors = [{ name="Jerrold Koh"}]
description = "A package for Kmeans clustering with many different distance metrics"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]



